#!/usr/bin/env python3
"""
Regenerate web/data.js from a fresh scrape of the VaultX collection.

Used by the daily GitHub Actions job. Scrapes the logged-in B2B catalog
(true B2B product list, availability and pricing) when a session is available
via --har or the VAULTX_B2B_COOKIE env var (a raw Cookie header string, e.g.
from a repo secret). Without a session it falls back to the public
online-store feed (MSRP + public availability only).

Usage:
    py build_web_data.py
    py build_web_data.py --har session.har
    py build_web_data.py --collection zip-binders --out web/data.js
"""

import argparse
import datetime as dt
import json
import sys

import requests

import scrape_vaultx as vx

# Products that are NOT in the public collection feed (login-gated, so they
# 404 anonymously and the unattended cron can't fetch them). Hard-coded so they
# always appear on the site. MSRP matches their Metallic siblings; B2B pricing
# is from a logged-in capture. Update status/prices here if they change.
EXTRA_ROWS = [
    # Just Pink (4 / 9 / 12 pocket) - MSRP matches Metallic siblings by size.
    {"size": "4-Pocket Exo-Tec® Zip Binder Just Pink", "color": "Just Pink",
     "sku": "VX-EX01-04MPK", "price": 16.99, "available": False,
     "status": "Sold Out", "b2b_min1": 13.34, "b2b_breaks": [[12, 12.01]]},
    {"size": "9-Pocket Exo-Tec® Zip Binder Just Pink", "color": "Just Pink",
     "sku": "VX-EX01-09MPK", "price": 23.99, "available": False,
     "status": "Sold Out", "b2b_min1": 19.44, "b2b_breaks": [[12, 17.49]]},
    {"size": "12-Pocket Exo-Tec® Zip Binder Just Pink", "color": "Just Pink",
     "sku": "VX-EX01-12MPK", "price": 28.99, "available": False,
     "status": "Sold Out", "b2b_min1": 22.46, "b2b_breaks": [[12, 20.21]]},
    # Just Purple (4 / 9 / 12 pocket)
    {"size": "4-Pocket Exo-Tec® Zip Binder Just Purple", "color": "Just Purple",
     "sku": "VX-EX01-04MPR", "price": 16.99, "available": False,
     "status": "Sold Out", "b2b_min1": 13.34, "b2b_breaks": [[12, 12.01]]},
    {"size": "9-Pocket Exo-Tec® Zip Binder Just Purple", "color": "Just Purple",
     "sku": "VX-EX01-09MPR", "price": 23.99, "available": False,
     "status": "Sold Out", "b2b_min1": 19.44, "b2b_breaks": [[12, 17.49]]},
    {"size": "12-Pocket Exo-Tec® Zip Binder Just Purple", "color": "Just Purple",
     "sku": "VX-EX01-12MPR", "price": 28.99, "available": False,
     "status": "Sold Out", "b2b_min1": 22.46, "b2b_breaks": [[12, 20.21]]},
]


def extra_rows(include_b2b, existing_skus=frozenset()):
    """Return the hard-coded extra products, with or without B2B pricing.

    Skips SKUs already present in the scraped rows so a logged-in B2B scrape
    (which sees the login-gated products directly) doesn't duplicate them.
    """
    out = []
    for e in EXTRA_ROWS:
        if e["sku"] in existing_skus:
            continue
        r = dict(e)
        if not include_b2b:
            r["b2b_min1"] = None
            r["b2b_breaks"] = []
        out.append(r)
    return out


def write_web_data(rows, collection, out_path, generated_by="build_web_data.py"):
    """Write the front-end data file (web/data.js) from scraped rows.

    Shared by build_web_data.py (public snapshot) and make_b2b_site.py (B2B).
    """
    data = {
        "generated": dt.datetime.now().strftime("%Y-%m-%d"),
        "collection": collection,
        "items": [
            {
                "size": r["size"],
                "color": r["color"],
                "sku": r["sku"],
                "msrp": r["price"],
                "b2b_min1": r["b2b_min1"],
                "breaks": r["b2b_breaks"],
                "status": r["status"],
            }
            for r in rows
        ],
    }
    js = (
        f"// Hard-coded VaultX {collection} stock snapshot "
        f"(generated {data['generated']}).\n"
        f"// Auto-generated by {generated_by} - do not edit by hand.\n"
        "const STOCK = " + json.dumps(data, ensure_ascii=False, indent=2) + ";\n"
    )
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(js)
    in_stock = sum(1 for r in rows if r["status"] == "In Stock")
    print(f"Wrote {out_path}: {len(rows)} items, {in_stock} in stock.")
    return data


def main():
    parser = argparse.ArgumentParser(description="Regenerate web/data.js")
    parser.add_argument("--collection", default=vx.DEFAULT_COLLECTION)
    parser.add_argument("--out", default="web/data.js")
    parser.add_argument("--har", default=None,
                        help="HAR from a logged-in us.b2b.vaultx.com session; "
                             "scrapes the true B2B catalog instead of the "
                             "public feed")
    args = parser.parse_args()

    public_products = []
    try:
        public_products = vx.fetch_products(args.collection)
    except requests.RequestException as e:
        # Only fatal if we also lack a B2B session to scrape from.
        print(f"WARNING: public feed unavailable ({e}).", file=sys.stderr)

    session = vx.resolve_session(args.har)

    rows = None
    if session:
        cookie, user_agent, source = session
        print(f"Using B2B session from {source}.")
        try:
            products, b2b_map = vx.fetch_b2b_catalog(
                args.collection, cookie, user_agent,
                vx.msrp_map(public_products))
            rows = vx.build_rows(products, b2b_map=b2b_map)
            rows += extra_rows(include_b2b=True,
                               existing_skus={r["sku"] for r in rows})
            print(f"Scraped B2B catalog: {len(products)} products.")
        except (ValueError, requests.RequestException) as e:
            print(f"WARNING: B2B scrape failed ({e}); falling back to the "
                  "public feed.", file=sys.stderr)

    if rows is None:
        if not public_products:
            print("ERROR: no data from either the B2B session or the public "
                  "feed; keeping the existing snapshot.", file=sys.stderr)
            raise SystemExit(1)
        rows = vx.build_rows(public_products)  # public -> b2b fields None/empty
        rows += extra_rows(include_b2b=False,
                           existing_skus={r["sku"] for r in rows})
    write_web_data(rows, args.collection, args.out)


if __name__ == "__main__":
    main()
