#!/usr/bin/env python3
"""
Regenerate web/data.js from a fresh public scrape of the VaultX collection.

Public pricing only (MSRP + stock status) so it runs fully unattended - no
logged-in session/HAR required. Used by the daily GitHub Actions job.

Usage:
    py build_web_data.py
    py build_web_data.py --collection zip-binders --out web/data.js
"""

import argparse
import datetime as dt
import json

import scrape_vaultx as vx


def main():
    parser = argparse.ArgumentParser(description="Regenerate web/data.js")
    parser.add_argument("--collection", default=vx.DEFAULT_COLLECTION)
    parser.add_argument("--out", default="web/data.js")
    args = parser.parse_args()

    products = vx.fetch_products(args.collection)
    rows = vx.build_rows(products)  # public only -> b2b fields are None/empty

    data = {
        "generated": dt.datetime.now().strftime("%Y-%m-%d"),
        "collection": args.collection,
        "items": [
            {
                "size": r["size"],
                "color": r["color"],
                "sku": r["sku"],
                "msrp": r["price"],
                "b2b_min1": r["b2b_min1"],
                "breaks": r["b2b_breaks"],
                "status": r["status"],
            }
            for r in rows
        ],
    }

    js = (
        f"// Hard-coded VaultX {args.collection} stock snapshot "
        f"(generated {data['generated']}).\n"
        "// Auto-generated by build_web_data.py - do not edit by hand.\n"
        "const STOCK = " + json.dumps(data, ensure_ascii=False, indent=2) + ";\n"
    )
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(js)

    in_stock = sum(1 for r in rows if r["status"] == "In Stock")
    print(f"Wrote {args.out}: {len(rows)} items, {in_stock} in stock.")


if __name__ == "__main__":
    main()
