#!/usr/bin/env python3
"""
Regenerate web/data.js from a fresh public scrape of the VaultX collection.

Public pricing only (MSRP + stock status) so it runs fully unattended - no
logged-in session/HAR required. Used by the daily GitHub Actions job.

Usage:
    py build_web_data.py
    py build_web_data.py --collection zip-binders --out web/data.js
"""

import argparse
import datetime as dt
import json

import scrape_vaultx as vx

# Products that are NOT in the public collection feed (login-gated, so they
# 404 anonymously and the unattended cron can't fetch them). Hard-coded so they
# always appear on the site. MSRP matches their Metallic siblings; B2B pricing
# is from a logged-in capture. Update status/prices here if they change.
EXTRA_ROWS = [
    # Just Pink (4 / 9 / 12 pocket) - MSRP matches Metallic siblings by size.
    {"size": "4-Pocket Exo-Tec® Zip Binder Just Pink", "color": "Just Pink",
     "sku": "VX-EX01-04MPK", "price": 16.99, "available": False,
     "status": "Sold Out", "b2b_min1": 13.34, "b2b_breaks": [[12, 12.01]]},
    {"size": "9-Pocket Exo-Tec® Zip Binder Just Pink", "color": "Just Pink",
     "sku": "VX-EX01-09MPK", "price": 23.99, "available": False,
     "status": "Sold Out", "b2b_min1": 19.44, "b2b_breaks": [[12, 17.49]]},
    {"size": "12-Pocket Exo-Tec® Zip Binder Just Pink", "color": "Just Pink",
     "sku": "VX-EX01-12MPK", "price": 28.99, "available": False,
     "status": "Sold Out", "b2b_min1": 22.46, "b2b_breaks": [[12, 20.21]]},
    # Just Purple (4 / 9 / 12 pocket)
    {"size": "4-Pocket Exo-Tec® Zip Binder Just Purple", "color": "Just Purple",
     "sku": "VX-EX01-04MPR", "price": 16.99, "available": False,
     "status": "Sold Out", "b2b_min1": 13.34, "b2b_breaks": [[12, 12.01]]},
    {"size": "9-Pocket Exo-Tec® Zip Binder Just Purple", "color": "Just Purple",
     "sku": "VX-EX01-09MPR", "price": 23.99, "available": False,
     "status": "Sold Out", "b2b_min1": 19.44, "b2b_breaks": [[12, 17.49]]},
    {"size": "12-Pocket Exo-Tec® Zip Binder Just Purple", "color": "Just Purple",
     "sku": "VX-EX01-12MPR", "price": 28.99, "available": False,
     "status": "Sold Out", "b2b_min1": 22.46, "b2b_breaks": [[12, 20.21]]},
]


def extra_rows(include_b2b):
    """Return the hard-coded extra products, with or without B2B pricing."""
    out = []
    for e in EXTRA_ROWS:
        r = dict(e)
        if not include_b2b:
            r["b2b_min1"] = None
            r["b2b_breaks"] = []
        out.append(r)
    return out


def write_web_data(rows, collection, out_path, generated_by="build_web_data.py"):
    """Write the front-end data file (web/data.js) from scraped rows.

    Shared by build_web_data.py (public snapshot) and make_b2b_site.py (B2B).
    """
    data = {
        "generated": dt.datetime.now().strftime("%Y-%m-%d"),
        "collection": collection,
        "items": [
            {
                "size": r["size"],
                "color": r["color"],
                "sku": r["sku"],
                "msrp": r["price"],
                "b2b_min1": r["b2b_min1"],
                "breaks": r["b2b_breaks"],
                "status": r["status"],
            }
            for r in rows
        ],
    }
    js = (
        f"// Hard-coded VaultX {collection} stock snapshot "
        f"(generated {data['generated']}).\n"
        f"// Auto-generated by {generated_by} - do not edit by hand.\n"
        "const STOCK = " + json.dumps(data, ensure_ascii=False, indent=2) + ";\n"
    )
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(js)
    in_stock = sum(1 for r in rows if r["status"] == "In Stock")
    print(f"Wrote {out_path}: {len(rows)} items, {in_stock} in stock.")
    return data


def main():
    parser = argparse.ArgumentParser(description="Regenerate web/data.js")
    parser.add_argument("--collection", default=vx.DEFAULT_COLLECTION)
    parser.add_argument("--out", default="web/data.js")
    args = parser.parse_args()

    products = vx.fetch_products(args.collection)
    rows = vx.build_rows(products)  # public only -> b2b fields are None/empty
    rows += extra_rows(include_b2b=False)  # login-gated products (public view)
    write_web_data(rows, args.collection, args.out)


if __name__ == "__main__":
    main()
