// Hard-coded VaultX zip-binders stock snapshot (generated 2026-07-23).
// Auto-generated by build_web_data.py - do not edit by hand.
const STOCK = {
  "generated": "2026-07-23",
  "collection": "zip-binders",
  "items": [
    {
      "size": "9-Pocket Exo-Tec® Zip Binder",
      "color": "Signature Black",
      "sku": "VX-EX01-09BK",
      "msrp": 31.99,
      "b2b_min1": 18.55,
      "breaks": [
        [
          12,
          16.69
        ]
      ],
      "status": "In Stock"
    },
    {
      "size": "9-Pocket Exo-Tec® Zip Binder",
      "color": "Royal Blue",
      "sku": "VX-EX01-09BL",
      "msrp": 31.99,
      "b2b_min1": 18.55,
      "breaks": [
        [
          12,
          16.69
        ]
      ],
      "status": "In Stock"
    },
    {
      "size": "9-Pocket Exo-Tec® Zip Binder",
      "color": "Forest Green",
      "sku": "VX-EX01-09GN",
      "msrp": 31.99,
      "b2b_min1": 18.55,
      "breaks": [
        [
          12,
          16.69
        ]
      ],
      "status": "In Stock"
    },
    {
      "size": "9-Pocket Exo-Tec® Zip Binder",
      "color": "Fire Red",
      "sku": "VX-EX01-09RD",
      "msrp": 31.99,
      "b2b_min1": 18.55,
      "breaks": [
        [
          12,
          16.69
        ]
      ],
      "status": "In Stock"
    },
    {
      "size": "9-Pocket Exo-Tec® Zip Binder",
      "color": "Ocean Blue",
      "sku": "VX-EX01-09TE",
      "msrp": 31.99,
      "b2b_min1": 18.55,
      "breaks": [
        [
          12,
          16.69
        ]
      ],
      "status": "In Stock"
    },
    {
      "size": "9-Pocket Exo-Tec® Zip Binder",
      "color": "Sunrise Yellow",
      "sku": "VX-EX01-09YL",
      "msrp": 31.99,
      "b2b_min1": 18.55,
      "breaks": [
        [
          12,
          16.69
        ]
      ],
      "status": "In Stock"
    },
    {
      "size": "12-Pocket Exo-Tec® Zip Binder",
      "color": "Signature Black",
      "sku": "VX-EX01-12BK",
      "msrp": 35.99,
      "b2b_min1": 21.67,
      "breaks": [
        [
          12,
          19.5
        ]
      ],
      "status": "In Stock"
    },
    {
      "size": "12-Pocket Exo-Tec® Zip Binder",
      "color": "Royal Blue",
      "sku": "VX-EX01-12BL",
      "msrp": 35.99,
      "b2b_min1": 21.67,
      "breaks": [
        [
          12,
          19.5
        ]
      ],
      "status": "In Stock"
    },
    {
      "size": "12-Pocket Exo-Tec® Zip Binder",
      "color": "Forest Green",
      "sku": "VX-EX01-12GN",
      "msrp": 35.99,
      "b2b_min1": 21.67,
      "breaks": [
        [
          12,
          19.5
        ]
      ],
      "status": "In Stock"
    },
    {
      "size": "12-Pocket Exo-Tec® Zip Binder",
      "color": "Fire Red",
      "sku": "VX-EX01-12RD",
      "msrp": 35.99,
      "b2b_min1": 21.67,
      "breaks": [
        [
          12,
          19.5
        ]
      ],
      "status": "In Stock"
    },
    {
      "size": "12-Pocket Exo-Tec® Zip Binder",
      "color": "Ocean Blue",
      "sku": "VX-EX01-12TE",
      "msrp": 35.99,
      "b2b_min1": 21.67,
      "breaks": [
        [
          12,
          19.5
        ]
      ],
      "status": "In Stock"
    },
    {
      "size": "12-Pocket Exo-Tec® Zip Binder",
      "color": "Sunrise Yellow",
      "sku": "VX-EX01-12YL",
      "msrp": 35.99,
      "b2b_min1": 21.67,
      "breaks": [
        [
          12,
          19.5
        ]
      ],
      "status": "In Stock"
    },
    {
      "size": "4-Pocket Exo-Tec® Zip Binder",
      "color": "Signature Black",
      "sku": "VX-EX01-04BK",
      "msrp": 24.99,
      "b2b_min1": 12.14,
      "breaks": [
        [
          12,
          10.93
        ]
      ],
      "status": "In Stock"
    },
    {
      "size": "4-Pocket Exo-Tec® Zip Binder",
      "color": "Royal Blue",
      "sku": "VX-EX01-04BL",
      "msrp": 24.99,
      "b2b_min1": 12.14,
      "breaks": [
        [
          12,
          10.93
        ]
      ],
      "status": "Sold Out"
    },
    {
      "size": "4-Pocket Exo-Tec® Zip Binder",
      "color": "Forest Green",
      "sku": "VX-EX01-04GN",
      "msrp": 24.99,
      "b2b_min1": 12.14,
      "breaks": [
        [
          12,
          10.93
        ]
      ],
      "status": "Sold Out"
    },
    {
      "size": "4-Pocket Exo-Tec® Zip Binder",
      "color": "Fire Red",
      "sku": "VX-EX01-04RD",
      "msrp": 24.99,
      "b2b_min1": 12.14,
      "breaks": [
        [
          12,
          10.93
        ]
      ],
      "status": "In Stock"
    },
    {
      "size": "4-Pocket Exo-Tec® Zip Binder",
      "color": "Ocean Blue",
      "sku": "VX-EX01-04TE",
      "msrp": 24.99,
      "b2b_min1": 12.14,
      "breaks": [
        [
          12,
          10.93
        ]
      ],
      "status": "Sold Out"
    },
    {
      "size": "4-Pocket Exo-Tec® Zip Binder",
      "color": "Sunrise Yellow",
      "sku": "VX-EX01-04YL",
      "msrp": 24.99,
      "b2b_min1": 12.14,
      "breaks": [
        [
          12,
          10.93
        ]
      ],
      "status": "Sold Out"
    },
    {
      "size": "12-Pocket Exo-Tec® Zip Binder XL",
      "color": "Signature Black",
      "sku": "VX-EX01-12XLBK",
      "msrp": 38.99,
      "b2b_min1": 23.22,
      "breaks": [
        [
          10,
          20.9
        ]
      ],
      "status": "In Stock"
    },
    {
      "size": "12-Pocket Exo-Tec® Zip Binder XL",
      "color": "Royal Blue",
      "sku": "VX-EX01-12XLBL",
      "msrp": 38.99,
      "b2b_min1": 23.22,
      "breaks": [
        [
          10,
          20.9
        ]
      ],
      "status": "In Stock"
    },
    {
      "size": "12-Pocket Exo-Tec® Zip Binder XL",
      "color": "Forest Green",
      "sku": "VX-EX01-12XLGN",
      "msrp": 38.99,
      "b2b_min1": 23.22,
      "breaks": [
        [
          10,
          20.9
        ]
      ],
      "status": "In Stock"
    },
    {
      "size": "12-Pocket Exo-Tec® Zip Binder XL",
      "color": "Fire Red",
      "sku": "VX-EX01-12XLRD",
      "msrp": 38.99,
      "b2b_min1": 23.22,
      "breaks": [
        [
          10,
          20.9
        ]
      ],
      "status": "In Stock"
    },
    {
      "size": "12-Pocket Exo-Tec® Zip Binder XL",
      "color": "Ocean Blue",
      "sku": "VX-EX01-12XLTE",
      "msrp": 38.99,
      "b2b_min1": 23.22,
      "breaks": [
        [
          10,
          20.9
        ]
      ],
      "status": "In Stock"
    },
    {
      "size": "12-Pocket Exo-Tec® Zip Binder XL",
      "color": "Sunrise Yellow",
      "sku": "VX-EX01-12XLYL",
      "msrp": 38.99,
      "b2b_min1": 23.22,
      "breaks": [
        [
          10,
          20.9
        ]
      ],
      "status": "In Stock"
    },
    {
      "size": "16-Pocket Exo-Tec® Zip Binder XXL",
      "color": "Signature Black",
      "sku": "VX-EX01-16BK",
      "msrp": 42.99,
      "b2b_min1": 24.07,
      "breaks": [
        [
          5,
          21.68
        ]
      ],
      "status": "In Stock"
    },
    {
      "size": "16-Pocket Exo-Tec® Zip Binder XXL",
      "color": "Royal Blue",
      "sku": "VX-EX01-16BL",
      "msrp": 42.99,
      "b2b_min1": 24.07,
      "breaks": [
        [
          5,
          21.68
        ]
      ],
      "status": "Sold Out"
    },
    {
      "size": "16-Pocket Exo-Tec® Zip Binder XXL",
      "color": "Forest green",
      "sku": "VX-EX01-16GN",
      "msrp": 42.99,
      "b2b_min1": 24.07,
      "breaks": [
        [
          5,
          21.68
        ]
      ],
      "status": "Sold Out"
    },
    {
      "size": "16-Pocket Exo-Tec® Zip Binder XXL",
      "color": "Fire Red",
      "sku": "VX-EX01-16RD",
      "msrp": 42.99,
      "b2b_min1": 24.07,
      "breaks": [
        [
          5,
          21.68
        ]
      ],
      "status": "Sold Out"
    },
    {
      "size": "16-Pocket Exo-Tec® Zip Binder XXL",
      "color": "Ocean Blue",
      "sku": "VX-EX01-16TE",
      "msrp": 42.99,
      "b2b_min1": 24.07,
      "breaks": [
        [
          5,
          21.68
        ]
      ],
      "status": "Sold Out"
    },
    {
      "size": "16-Pocket Exo-Tec® Zip Binder XXL",
      "color": "Sunrise Yellow",
      "sku": "VX-EX01-16YL",
      "msrp": 42.99,
      "b2b_min1": 24.07,
      "breaks": [
        [
          5,
          21.68
        ]
      ],
      "status": "Sold Out"
    },
    {
      "size": "9-Pocket Exo-Tec® Zip Binder Metallic Red",
      "color": "Metallic Red",
      "sku": "VX-EX01-09RDMT",
      "msrp": 23.99,
      "b2b_min1": 19.44,
      "breaks": [
        [
          12,
          17.49
        ]
      ],
      "status": "In Stock"
    },
    {
      "size": "9-Pocket Exo-Tec® Zip Binder Metallic Green",
      "color": "Metallic Green",
      "sku": "VX-EX01-09GNMT",
      "msrp": 23.99,
      "b2b_min1": 19.44,
      "breaks": [
        [
          12,
          17.49
        ]
      ],
      "status": "In Stock"
    },
    {
      "size": "12-Pocket Exo-Tec® Zip Binder Metallic Red",
      "color": "Metallic Red",
      "sku": "VX-EX01-12RDMT",
      "msrp": 28.99,
      "b2b_min1": 22.46,
      "breaks": [
        [
          12,
          20.21
        ]
      ],
      "status": "In Stock"
    },
    {
      "size": "12-Pocket Exo-Tec Zip Binder Metallic Green",
      "color": "Metallic Green",
      "sku": "VX-EX01-12GNMT",
      "msrp": 28.99,
      "b2b_min1": 22.46,
      "breaks": [
        [
          12,
          20.21
        ]
      ],
      "status": "In Stock"
    },
    {
      "size": "9-Pocket Exo-Tec® Zip Binder Just Purple",
      "color": "Just Purple",
      "sku": "VX-EX01-09MPR",
      "msrp": null,
      "b2b_min1": 19.44,
      "breaks": [
        [
          12,
          17.49
        ]
      ],
      "status": "Sold Out"
    },
    {
      "size": "9-Pocket Exo-Tec® Zip Binder Just Pink",
      "color": "Just Pink",
      "sku": "VX-EX01-09MPK",
      "msrp": null,
      "b2b_min1": 19.44,
      "breaks": [
        [
          12,
          17.49
        ]
      ],
      "status": "Sold Out"
    },
    {
      "size": "12-Pocket Exo-Tec® Zip Binder Just Pink",
      "color": "Just Pink",
      "sku": "VX-EX01-12MPK",
      "msrp": null,
      "b2b_min1": 22.46,
      "breaks": [
        [
          12,
          20.21
        ]
      ],
      "status": "Sold Out"
    },
    {
      "size": "12-Pocket Exo-Tec® Zip Binder Just Purple",
      "color": "Just Purple",
      "sku": "VX-EX01-12MPR",
      "msrp": null,
      "b2b_min1": 22.46,
      "breaks": [
        [
          12,
          20.21
        ]
      ],
      "status": "Sold Out"
    },
    {
      "size": "4-Pocket Exo-Tec® Zip Binder Just Purple",
      "color": "Just Purple",
      "sku": "VX-EX01-04MPR",
      "msrp": null,
      "b2b_min1": 13.34,
      "breaks": [
        [
          12,
          12.01
        ]
      ],
      "status": "Sold Out"
    },
    {
      "size": "4-Pocket Exo-Tec® Zip Binder Just Pink",
      "color": "Just Pink",
      "sku": "VX-EX01-04MPK",
      "msrp": null,
      "b2b_min1": 13.34,
      "breaks": [
        [
          12,
          12.01
        ]
      ],
      "status": "Sold Out"
    },
    {
      "size": "12-Pocket Exo-Tec® Zip Binder ME1",
      "color": "ME1 (First Edition)",
      "sku": "ME-EX01-1201",
      "msrp": 32.99,
      "b2b_min1": 22.46,
      "breaks": [],
      "status": "Sold Out"
    },
    {
      "size": "12-Pocket Exo-Tec® Zip Binder ME1",
      "color": "ME1 (Unlimited)",
      "sku": "ME-EX01-1201U",
      "msrp": 32.99,
      "b2b_min1": 22.46,
      "breaks": [],
      "status": "Sold Out"
    },
    {
      "size": "9-Pocket Exo-Tec® Zip Binder ME1",
      "color": "ME1 (First Edition)",
      "sku": "ME-EX01-0901",
      "msrp": 26.99,
      "b2b_min1": 19.44,
      "breaks": [],
      "status": "Sold Out"
    },
    {
      "size": "9-Pocket Exo-Tec® Zip Binder ME1",
      "color": "ME1 (Unlimited)",
      "sku": "ME-EX01-0901U",
      "msrp": 26.99,
      "b2b_min1": 19.44,
      "breaks": [],
      "status": "Sold Out"
    },
    {
      "size": "4-Pocket Exo-Tec® Zip Binder Metallic Red",
      "color": "Metallic Red",
      "sku": "VX-EX01-04RDMT",
      "msrp": 16.99,
      "b2b_min1": 13.34,
      "breaks": [
        [
          12,
          12.01
        ]
      ],
      "status": "Sold Out"
    },
    {
      "size": "4-Pocket Exo-Tec® Zip Binder Metallic Green",
      "color": "Metallic Green",
      "sku": "VX-EX01-04GNMT",
      "msrp": 16.99,
      "b2b_min1": 13.34,
      "breaks": [
        [
          12,
          12.01
        ]
      ],
      "status": "Sold Out"
    }
  ]
};
